rule register_contacts:
    input:
        in_im=bids(
            root=config["output_dir"],
            suffix="dseg.nii.gz",
            desc="contacts_nnUNet",
            **inputs["post_ct"].wildcards,
        ),
        ref_im=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        transform_matrix=get_reg_matrix(),
    output:
        out_im=bids(
            root=config["output_dir"],
            suffix="dseg.nii.gz",
            space="T1w",
            desc="contacts_nnUNet",
            **inputs["post_ct"].wildcards,
        ),
    conda:
        "../envs/image_processing.yaml"
    script:
        "../scripts/apply_registration.py"


rule contacts_qc:
    input:
        ct_img=get_registered_ct_image(),
        t1w_img=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        contact_fcsv_labelled=bids(
            root=config["output_dir"],
            datatype="slicer_fcsv",
            suffix="labelled_contactseg.fcsv",
            **inputs["post_ct"].wildcards,
        ),
        planned_fcsv=bids(
            root=config["bids_dir"],
            suffix="planned",
            extension=".fcsv",
            **inputs["post_ct"].wildcards,
        ),
    output:
        html=bids(
            root=config["output_dir"],
            datatype="qc",
            desc="contactseg",
            suffix="qc.html",
            **inputs["post_ct"].wildcards,
        ),
    conda:
        "../envs/analysis.yaml"
    script:
        "../scripts/contacts_qc.py"
